Viewmodel shifting improvement
mikkokko/csldr pull request #5
Opened 2022-11-28 11:59 UTC by Polarhigh

This change removes the viewmodel's z offset by -1 while viewmodel_shift is active

2022-11-28 15:03 UTC, mikkokko requested changes
This wold be good to have. I left a few comments on things that should be looked into before merging.

2022-11-28 23:08 UTC, Polarhigh commented
> This wold be good to have. I left a few comments on things that should be looked into before merging.

Got it, I'll make edits in the week👌

2022-12-03 10:26 UTC, Polarhigh commented on csldr/maths.c
> +void MatrixSetColumn(const vec3_t in, int column, matrix3x4_t out)
I did some refactoring, removed unnecessary functions, and made the naming of matrix operations clearer. But I did not use Vec3_Copy. Instead, I added GetMatrixTranslation and SetTranslationMatrix. I think it's better to use functions with that name in the context of matrices.

2022-12-03 11:36 UTC, mikkokko approved these changes

2022-12-03 11:37 UTC, merged